---
- hosts: 127.0.0.1
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/dockutil.yml
    - include: tasks/ruby.yml
    - include: tasks/post_install.yml

    #- include: tasks/preferences.yml

    # TODO: Use sudo once .osx can be run via root with no user interaction.
    - name: Run osx defaults config and friends
      shell: files/osx
      changed_when: false
