---
# http://ryanbigg.com/2015/06/mac-os-x-ruby-ruby-install-chruby-and-you/

- command: test -x '~/.rubies/ruby-{{ ruby_version }}/bin/ruby'
  register: default_ruby_exists

- name: 'Install Ruby: {{ ruby_version }}'
  command: '{{ item }}'
  with_items:
    - source /usr/local/opt/chruby/share/chruby/chruby.sh
    - source /usr/local/opt/chruby/share/chruby/auto.sh
    - 'ruby-install ruby {{ ruby_version }}'
    - echo '{{ ruby_version }}' > ~/.ruby-version
  when: default_ruby_exists|failed
